version: '3.9'

services:
  l-mysql:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    container_name: l-mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql

volumes:
  db:
    driver: local